--icons@lucide
loadstring(game:HttpGet("https://raw.githubusercontent.com/aksaraax/Adios/refs/heads/main/Linoria/lucide/icons.luau"))()
--library@obsidian
loadstring(game:HttpGet("https://raw.githubusercontent.com/aksaraax/Adios/refs/heads/main/Linoria/library.luau"))()
--savemanager@obsidian
loadstring(game:HttpGet("https://raw.githubusercontent.com/aksaraax/Adios/refs/heads/main/Linoria/savemanager.luau"))()
